force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <customHelpPage>FinalStage_Employee</customHelpPage>
    <label>Employee</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Image_Upload__c.field-meta.xml
<CustomField>
    <fullName>Image_Upload__c</fullName>
    <label>Image Upload</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PhotoUpload.cls
public class PhotoUpload {
//public class ContactPhotoExtension { 

public Employee__c cont;
public blob picture {get;set;}

 public PhotoUpload(ApexPages.StandardController st){
  this.cont = (Employee__c) st.getRecord();
 
 }
 public PageReference save() {
 PageReference pr ;
  try{
     insert cont;
     if(picture !=null) {
      Attachment attach = new Attachment();
        attach.body = picture;
        attach.name = 'Employee_' + cont.id + '.jpg';
        attach.parentid = cont.id;
        attach.ContentType = 'application/jpg';
        insert attach;
     cont.Image_Upload__c = '/servlet/servlet.FileDownload?file='+ attach.id;
                update cont;
       Pr = new PageReference('/'+cont.id);
       pr.setRedirect(true);
    }
   
  
  } catch(Exception  e){
   system.debug('Error Message==>'+e);
  }
 
  return pr;
 } 


}