force-app/main/default/objects/Admission__c/Admission__c.object-meta.xml
<CustomObject>
    <label>Admission</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Admission Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Admissions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Admission__c/fields/Student_Name__c.field-meta.xml
<CustomField>
    <fullName>Student_Name__c</fullName>
    <label>Student Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/checkAccount.cls
@RestResource(urlMapping='/ShowAdmissionDetails/*')
global class checkAccount{

    @Httpget
    global static List<Admission__c> getAccount(){
        List<Admission__c> lst;
        try{
            lst = [SELECT Student_Name__c, Gender__c from Admission__c];
            return lst;
        }
        catch(Exception ex)
        {
            system.debug('Error'+ex.getMessage());
        }
        return lst;
    
    }
    
}