force-app/main/default/objects/Registration_Form__c/Registration_Form__c.object-meta.xml
<CustomObject>
    <label>Registration Form</label>
    <nameField>
        <label>Admission Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Registration Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration_Form__c/fields/Parent_Name__c.field-meta.xml
<CustomField>
    <fullName>Parent_Name__c</fullName>
    <label>Parent Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration_Form__c/fields/Student_Name__c.field-meta.xml
<CustomField>
    <fullName>Student_Name__c</fullName>
    <label>Student Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/mysearchController.cls
public class mysearchController {
    @AuraEnabled
    public static  List<Registration_Form__c> mysearch(String searchKeyWord) {
        String searchKey = '%' + searchKeyWord + '%';
        List < Registration_Form__c > returnLists = new List < Registration_Form__c > ();
        List < Registration_Form__c > stdlst = [select id, Student_Name__c, Parent_Name__c, Class_Name__c from Registration_Form__c where Student_Name__c LIKE: searchKey];
        for (Registration_Form__c RGS: stdlst) {
         returnLists.add(RGS);
  }
 		return returnLists;
    }   

//Method for update records inline editing
	@AuraEnabled
	public static List<Registration_Form__c> updateform(List<Registration_Form__c> lstform){
    	update lstform;
    	return lstform;
	}
}